//! Curated prelude content for the reader-workload fixture.
//!
//! GENERATED by `fixtures/reader-workload/tools/build_fixture_data.py`
//! (authoring tool, not part of the Rust library, its tests, or any
//! normal generation/verification flow). Do not edit this file by
//! hand: change the generator, rerun it, and let the fixture
//! revision and manifest move together.
//!
//! Text is stored in logical Unicode order; Arabic/Hebrew content is
//! never visually pre-reversed. Byte offsets are UTF-8 offsets
//! computed once by the generator and verified by fixture tests.

use crate::workload::{BaseDirection, InlineStyle, StyleRun};
use PreludeItem::{Heading, Image, Paragraph};

/// Fixture revision stamped on the manifest and every workload.
pub const FIXTURE_REVISION: &str = "reader-workload-fx-3";

/// Portable, fixture-root-relative path of the single workload image.
pub const IMAGE_ASSET_PATH: &str = "assets/images/reader-sample.png";

/// Intrinsic pixel dimensions of the generated PNG.
pub const IMAGE_INTRINSIC: (u32, u32) = (480, 320);

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PreludeItem {
    Heading {
        id: &'static str,
        text: &'static str,
        level: u8,
    },
    Paragraph {
        id: &'static str,
        text: &'static str,
        base_direction: BaseDirection,
        style_runs: &'static [StyleRun],
    },
    Image {
        id: &'static str,
        asset_path: &'static str,
    },
}

pub const P_00001_BOLD_RUN: StyleRun = StyleRun {
    start_byte: 11,
    end_byte: 26,
    style: InlineStyle::Bold,
};
pub const P_00002_ITALIC_RUN: StyleRun = StyleRun {
    start_byte: 87,
    end_byte: 92,
    style: InlineStyle::Italic,
};
pub const P_00006_BOLD_RUN: StyleRun = StyleRun {
    start_byte: 70,
    end_byte: 73,
    style: InlineStyle::Bold,
};
pub const P_00008_BOLD_RUN: StyleRun = StyleRun {
    start_byte: 4,
    end_byte: 13,
    style: InlineStyle::Bold,
};
pub const P_00009_BOLD_RUN: StyleRun = StyleRun {
    start_byte: 22,
    end_byte: 35,
    style: InlineStyle::Bold,
};
pub const P_00009_ITALIC_RUN: StyleRun = StyleRun {
    start_byte: 43,
    end_byte: 55,
    style: InlineStyle::Italic,
};
pub const P_00010_ITALIC_RUN: StyleRun = StyleRun {
    start_byte: 56,
    end_byte: 69,
    style: InlineStyle::Italic,
};
pub const P_00012_BOLD_RUN: StyleRun = StyleRun {
    start_byte: 27,
    end_byte: 31,
    style: InlineStyle::Bold,
};

/// Ordered curated items: 2 headings, 12 paragraphs, 1 image block.
pub const PRELUDE: &[PreludeItem] = &[
    Heading {
        id: "h-0001",
        text: r#"Reader Workload Fixture"#,
        level: 1,
    },
    Paragraph {
        id: "p-00001",
        text: r#"The little stationery shop glowed beside the rain-soaked street as evening readers passed by."#,
        base_direction: BaseDirection::Ltr,
        style_runs: &[P_00001_BOLD_RUN],
    },
    Paragraph {
        id: "p-00002",
        text: r#"هذا نص تجريبي بالعربية، وفي وسطه الرقم 42 ومصطلح Latin، والكلمة مدرّسة تحمل علامة شدة."#,
        base_direction: BaseDirection::Rtl,
        style_runs: &[P_00002_ITALIC_RUN],
    },
    Paragraph {
        id: "p-00003",
        text: r#"(اא) 1-2"#,
        base_direction: BaseDirection::Rtl,
        style_runs: &[],
    },
    Paragraph {
        id: "p-00004",
        text: r#"אבג (def ابج) abc"#,
        base_direction: BaseDirection::Rtl,
        style_runs: &[],
    },
    Paragraph {
        id: "p-00005",
        text: r#"קטע עברית לבדיקה: מספרים 123 וגם English בתוך הטקסט."#,
        base_direction: BaseDirection::Rtl,
        style_runs: &[],
    },
    Paragraph {
        id: "p-00006",
        text: r#"日本語のテキストは横書きで表示され、Latin や数字 123 と混在します。折り返しは単語の境界に限定されません。"#,
        base_direction: BaseDirection::Ltr,
        style_runs: &[P_00006_BOLD_RUN],
    },
    Paragraph {
        id: "p-00007",
        text: r#"The words café and naïve remain decomposed in logical order."#,
        base_direction: BaseDirection::Ltr,
        style_runs: &[],
    },
    Paragraph {
        id: "p-00008",
        text: r#"The efficient staff finished the difficult briefing in the office."#,
        base_direction: BaseDirection::Ltr,
        style_runs: &[P_00008_BOLD_RUN],
    },
    Image {
        id: "img-0001",
        asset_path: IMAGE_ASSET_PATH,
    },
    Heading {
        id: "h-0002",
        text: r#"Styled Passages"#,
        level: 1,
    },
    Paragraph {
        id: "p-00009",
        text: r#"Normal text carries a bold emphasis and an italic aside before it continues normally."#,
        base_direction: BaseDirection::Ltr,
        style_runs: &[P_00009_BOLD_RUN, P_00009_ITALIC_RUN],
    },
    Paragraph {
        id: "p-00010",
        text: r#"The reader opens a long paragraph that will wrap across several lines at the narrow content width. Selection should be able to start inside the first wrapped line and end after the last one. Nothing in this paragraph depends on the renderer that will draw it later. The words stay in logical order from the first byte to the last. Wrapped line count is a layout observation for the UI tasks, not a property of this text. Copying this paragraph must reproduce these sentences exactly as stored."#,
        base_direction: BaseDirection::Ltr,
        style_runs: &[P_00010_ITALIC_RUN],
    },
    Paragraph {
        id: "p-00011",
        text: r#"Glyph probes: musical clef (U+1D11E) 𝄞, smiling face (U+1F642) 🙂; both are non-gating for the baseline font set."#,
        base_direction: BaseDirection::Ltr,
        style_runs: &[],
    },
    Paragraph {
        id: "p-00012",
        text: r#"Digit probes: Arabic-Indic ١-1 beside ASCII 6-6, mixed with Latin."#,
        base_direction: BaseDirection::Ltr,
        style_runs: &[P_00012_BOLD_RUN],
    },
];
