//! Named selection/copy reference cases for the reader-workload fixture.
//!
//! GENERATED by `fixtures/reader-workload/tools/build_fixture_data.py`.
//! Endpoints are stable text-item IDs plus zero-based UTF-8 byte
//! offsets; ranges are start-inclusive/end-exclusive.
//! `*_first_char: Option<char>` records the Unicode scalar expected
//! to start at each endpoint (`None` = endpoint at end-of-text) so
//! fixture tests detect text drift at the exact recorded coordinate.

use crate::reference::{Endpoint, SelectionCase};

/// The curated selection/copy reference cases, in fixture order.
pub fn cases() -> Vec<SelectionCase> {
    vec![
        SelectionCase {
            name: "collapsed",
            notes: r#"Zero-length selection: anchor and focus are the same byte offset; the copied text is empty."#,
            anchor: Endpoint {
                item_id: "p-00010".to_string(),
                byte_offset: 217,
            },
            anchor_first_char: Some('d'),
            focus: Endpoint {
                item_id: "p-00010".to_string(),
                byte_offset: 217,
            },
            focus_first_char: Some('d'),
        },
        SelectionCase {
            name: "style-boundary",
            notes: r#"Within one paragraph: starts inside the bold run, ends before the trailing plain tail; plain text between the styled runs is included."#,
            anchor: Endpoint {
                item_id: "p-00009".to_string(),
                byte_offset: 22,
            },
            anchor_first_char: Some('b'),
            focus: Endpoint {
                item_id: "p-00009".to_string(),
                byte_offset: 56,
            },
            focus_first_char: Some('b'),
        },
        SelectionCase {
            name: "long-within-paragraph",
            notes: r#"Long range inside one paragraph; at the 480 DIP content width it is intended to span more wrapped lines than one screen row shows."#,
            anchor: Endpoint {
                item_id: "p-00010".to_string(),
                byte_offset: 99,
            },
            anchor_first_char: Some('S'),
            focus: Endpoint {
                item_id: "p-00010".to_string(),
                byte_offset: 392,
            },
            focus_first_char: Some('n'),
        },
        SelectionCase {
            name: "adjacent-paragraphs",
            notes: r#"Two consecutive paragraphs joined by exactly one LF."#,
            anchor: Endpoint {
                item_id: "p-00005".to_string(),
                byte_offset: 0,
            },
            anchor_first_char: Some('ק'),
            focus: Endpoint {
                item_id: "p-00006".to_string(),
                byte_offset: 152,
            },
            focus_first_char: None,
        },
        SelectionCase {
            name: "cross-paragraph-partial",
            notes: r#"Selection starts mid-paragraph and ends mid-paragraph across the paragraph boundary."#,
            anchor: Endpoint {
                item_id: "p-00005".to_string(),
                byte_offset: 32,
            },
            anchor_first_char: Some('מ'),
            focus: Endpoint {
                item_id: "p-00006".to_string(),
                byte_offset: 77,
            },
            focus_first_char: Some('混'),
        },
        SelectionCase {
            name: "cross-image-heading",
            notes: r#"Range crosses an intervening image item (contributes no text, no separator) and a heading (contributes its text, joined with LF)."#,
            anchor: Endpoint {
                item_id: "p-00008".to_string(),
                byte_offset: 0,
            },
            anchor_first_char: Some('T'),
            focus: Endpoint {
                item_id: "p-00009".to_string(),
                byte_offset: 85,
            },
            focus_first_char: None,
        },
        SelectionCase {
            name: "across-viewport",
            notes: r#"Twelve paragraphs plus the intervening heading at the shared layout recipe exceed the 600 DIP viewport, so this range requires scrolling; the intervening image contributes nothing."#,
            anchor: Endpoint {
                item_id: "p-00001".to_string(),
                byte_offset: 0,
            },
            anchor_first_char: Some('T'),
            focus: Endpoint {
                item_id: "p-00012".to_string(),
                byte_offset: 67,
            },
            focus_first_char: None,
        },
        SelectionCase {
            name: "reversed",
            notes: r#"Same content as adjacent-paragraphs with anchor and focus swapped; the copied text is identical."#,
            anchor: Endpoint {
                item_id: "p-00006".to_string(),
                byte_offset: 152,
            },
            anchor_first_char: None,
            focus: Endpoint {
                item_id: "p-00005".to_string(),
                byte_offset: 0,
            },
            focus_first_char: Some('ק'),
        },
        SelectionCase {
            name: "rtl-mixed",
            notes: r#"Whole Arabic paragraph with Latin and digits embedded; stored in logical order."#,
            anchor: Endpoint {
                item_id: "p-00002".to_string(),
                byte_offset: 0,
            },
            anchor_first_char: Some('ه'),
            focus: Endpoint {
                item_id: "p-00002".to_string(),
                byte_offset: 150,
            },
            focus_first_char: None,
        },
        SelectionCase {
            name: "cjk",
            notes: r#"Whole Japanese paragraph with Latin and digits embedded."#,
            anchor: Endpoint {
                item_id: "p-00006".to_string(),
                byte_offset: 0,
            },
            anchor_first_char: Some('日'),
            focus: Endpoint {
                item_id: "p-00006".to_string(),
                byte_offset: 152,
            },
            focus_first_char: None,
        },
        SelectionCase {
            name: "combining",
            notes: r#"Range covers complete base-plus-combining-mark sequences; endpoints must not bisect a mark from its base."#,
            anchor: Endpoint {
                item_id: "p-00007".to_string(),
                byte_offset: 10,
            },
            anchor_first_char: Some('c'),
            focus: Endpoint {
                item_id: "p-00007".to_string(),
                byte_offset: 29,
            },
            focus_first_char: Some('r'),
        },
        SelectionCase {
            name: "supplementary",
            notes: r#"Range covers an astral-plane scalar (U+1D11E) so byte offsets and scalar indexing stay distinct."#,
            anchor: Endpoint {
                item_id: "p-00011".to_string(),
                byte_offset: 22,
            },
            anchor_first_char: Some('c'),
            focus: Endpoint {
                item_id: "p-00011".to_string(),
                byte_offset: 41,
            },
            focus_first_char: Some(','),
        },
    ]
}
